apiVersion: v1
kind: ReplicationController
metadata:
  name: spin-deck-v000
  namespace: spinnaker
  labels:
    app: spin
    stack: deck
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: spin-deck-v000
  template:
    metadata:
      labels:
        replication-controller: spin-deck-v000
        load-balancer-spin-deck: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/deck:master
          name: deck
          command:
            - /bin/bash
            - -c
          args:
            - "cp /opt/spinnaker/config/settings.js .; npm start"
          env:
            - name: DECK_HOST
              value: "0.0.0.0"
            - name: DECK_PORT
              value: "9000"
          ports:
            - containerPort: 9000
              name: deck
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
